Repository anitab-org/mentorship-backend, pull requests merged in 2018-07, with the labels that each got.

#69 Redo cancel mentorship request API
  app/api/dao/mentorship_relation.py
  app/api/resources/mentorship_relation.py
  docs/swagger.json
  tests/mentorship_relation/test_api_cancel_relation.py
  tests/mentorship_relation/test_dao_cancel_relation.py
Labels: Review Requested

#53 Add email verification feature
  README.md
  app/api/dao/user.py
  app/api/email_utils.py
  app/api/mail_extension.py
  app/api/models/user.py
  app/api/resources/user.py
  app/security.py
  config.py
  docs/swagger.json
  requirements.txt
  run.py
  templates/email_confirmation.html
  tests/base_test_case.py
  tests/users/test_api_resources.py
  tests/users/test_dao.py
Labels: Priority: HIGH, Review Requested

#74 APIs to list previous, current and pending mentorship relations
  app/api/dao/mentorship_relation.py
  app/api/resources/mentorship_relation.py
  docs/swagger.json
  tests/mentorship_relation/test_api_list_relations.py
  tests/mentorship_relation/test_dao_list_relations.py
Labels: Priority: MEDIUM, Work In Progress

#75 Restrict GET /users API to authenticated users
  app/api/models/user.py
  app/api/resources/user.py
  app/database/db_utils.py
  docs/swagger.json
  tests/users/test_api_authentication.py
  tests/users/test_api_list_users.py
  tests/users/test_api_resources.py
Labels: Review Requested

#79 Cron job to set a Mentorship Relation to completed state
  app/schedulers/__init__.py
  app/schedulers/background_scheduler.py
  app/schedulers/complete_mentorship_cron_job.py
  requirements.txt
  run.py
  tests/cron_job_functions/__init__.py
  tests/cron_job_functions/test_mentorship_completion_cron.py
Labels: Review Requested

#85 Fix bug of updating username already taken returning error 500
  app/api/dao/user.py
  app/api/resources/user.py
  docs/swagger.json
  tests/users/test_api_update_user.py
Labels: Review Requested

#95 Fixed User registration request data validation
  app/api/dao/user.py
  app/api/resources/user.py
  app/api/validations/__init__.py
  app/api/validations/user.py
  app/utils/validation_utils.py
  tests/users/test_validation_request_data.py
  tests/utils/test_email_validation.py
  tests/utils/test_username_validation.py
Labels: Review Requested

#105 Check kept on new password entered while changing password
  app/api/resources/user.py
  app/api/validations/user.py
  tests/users/test_validation_request_data.py
Labels: Review Requested

#118 Create quality_assurance.md
  .github/ISSUE_TEMPLATE/quality_assurance.md
Labels: Not Reviewed
