Repository anitab-org/mentorship-backend, pull requests merged in 2019-02, with the labels that each got.

#165 Implemented refresh tokens
  app/api/jwt_extension.py
  app/api/models/user.py
  app/api/resources/user.py
  config.py
  tests/test_app_config.py
  tests/test_utils.py
  tests/users/test_api_authentication.py
  tests/users/test_api_login.py
  tests/users/test_api_refresh.py
Labels: Review Requested

#179 docs: added doc strings for TaskDao class and its functions
  app/api/dao/task.py
Labels: Category: Documentation/Training

#182 Add doc strings for MentorshipRelationDAO class and its functions.
  app/api/dao/mentorship_relation.py
Labels: Category: Documentation/Training, Not Reviewed
