Repository anitab-org/mentorship-backend, pull requests merged in 2020-11, with the labels that each got.

#850 Performed manual testing and report PUT /user API
  docs/manual_tests/manual_tests_PUT_user.md
Labels: Status: Ready to Merge

#831 docs: add user search default values to Swagger UI
  app/api/resources/user.py
Labels: Status: Ready to Merge

#839 added TERMS AND CONDITIONS NOT CHECKED response
  app/api/resources/user.py
Labels: Status: Ready to Merge

#889 refactor: Auditing dependencies
  dev-requirements.txt
  requirements.txt
Labels: Status: Needs Review, dependencies

#813 swagger-cleanup
  app/api/models/mentorship_relation.py
  app/api/models/user.py
Labels: Open Source Hack, Status: Ready to Merge

#890 Performed manual testing and report GET /user/confirm_email/{token} A…
  app/api/resources/user.py
  docs/manual_tests/test_confirmation_token.md
Labels: Status: Ready to Merge

#924 fix: HTTP status codes fixed
  app/api/dao/task.py
  app/api/resources/mentorship_relation.py
  app/api/resources/user.py
Labels: Status: Ready to Merge
