Repository anitab-org/mentorship-backend, pull requests merged in 2020-03, with the labels that each got.

#455 Create quality assurance test cases md file
  docs/quality-assurance-test-cases.md
Labels: Category: Documentation/Training

#335 Added basic support for database migrations
  migrations/README
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  requirements.txt
  run.py
Labels: Priority: HIGH

#485 Add environment variables documentation
  docs/environment-variables.md
Labels: Category: Documentation/Training

#492 Create Quality Assurance table for Refresh token API
  docs/quality-assurance-test-cases.md
Labels: Category: Documentation/Training

#354 Added some type hints
  app/api/dao/admin.py
  app/api/dao/mentorship_relation.py
  app/api/dao/task.py
  app/api/dao/user.py
  app/database/models/mentorship_relation.py
  app/database/models/tasks_list.py
  app/database/models/user.py
  config.py
  run.py
Labels: Category: Coding

#508 Update Email max length
  app/database/models/user.py
Labels: Category: Coding
