Repository anitab-org/mentorship-backend, pull requests merged in 2020-08, with the labels that each got.

#605 Upgrade to flask-restx
  app/api/api_extension.py
  app/api/dao/user.py
  app/api/models/admin.py
  app/api/models/mentorship_relation.py
  app/api/models/user.py
  app/api/resources/admin.py
  app/api/resources/common.py
  app/api/resources/mentorship_relation.py
  app/api/resources/user.py
  requirements.txt
  tests/admin/test_api_list_admin_users.py
  tests/admin/test_api_remove_admin_user.py
  tests/mentorship_relation/test_api_list_relations.py
  tests/task_comments/test_api_get_task_comments.py
  tests/tasks/test_api_list_tasks.py
  tests/users/test_api_authentication.py
  tests/users/test_api_list_users.py
Labels: Status: Needs Review

#699 Fix: refactor HTTP error codes PUT / mentorship_relation/{request_id}/accept
  app/api/dao/mentorship_relation.py
  app/api/resources/mentorship_relation.py
  tests/mentorship_relation/test_api_accept_request.py
  tests/mentorship_relation/test_dao_accept_request.py
Labels: Status: Ready to Merge

#684 refactor: Fix HTTP status code for DELETE /mentorship_relation/{relation_id}/task/{task_id}/comment/{comment_id} and its tests
  app/api/dao/task_comment.py
  app/api/resources/mentorship_relation.py
  tests/task_comments/test_api_delete_task_comment.py
Labels: Status: Needs Testing

#707 chore: change imports to flask_restx
  tests/users/test_api_get_other_user.py
Labels: Status: Needs Testing, Status: Ready to Merge

#718 docs: add python 3.6 badge to README.md
  README.md
Labels: Status: Ready to Merge

#670 style: format comments of TaskCommentModel present in task_comment.py file
  app/database/models/task_comment.py
Labels: Status: Ready to Merge

#731 added MENTOR FIELD IS MISSING under responses
  app/api/resources/mentorship_relation.py
Labels: Status: Ready to Merge

#704 refactor: remove the expiry field
  app/api/models/user.py
Labels: Status: Ready to Merge

#700 Fix: refactor HTTP error codes DELETE /mentorship_relation/{request_id}
  app/api/dao/mentorship_relation.py
  app/api/resources/mentorship_relation.py
  tests/mentorship_relation/test_api_delete_request.py
  tests/mentorship_relation/test_dao_delete_request.py
Labels: Category: Coding, Status: Ready to Merge

#735 Chore: Use `--no-cache-dir` flag to `pip` in Dockerfiles, to save space
  Dockerfile
Labels: Status: Ready to Merge

#749 Style: Change to f-strings (fix#741)
  app/api/resources/admin.py
Labels: Status: Needs Testing
