Repository anitab-org/mentorship-backend, pull requests merged in 2020-06, with the labels that each got.

#589 Code : Upgrade psycopg2-binary to the latest version -issue 586
  requirements.txt
Labels: Status: Ready to Merge

#643 docs: show invalid email message for 400 code on Swagger
  app/api/resources/user.py
Labels: Status: Ready to Merge

#640 chore: add heroku deploy needs
  Procfile
  requirements.txt
Labels: Category: Coding, Status: Needs Review, Type: Maintenance

#649 refactor: HTTP error codes POST /mentorship_relation/send_request
  app/api/dao/mentorship_relation.py
  app/api/resources/mentorship_relation.py
  tests/mentorship_relation/test_api_send_request.py
Labels: Status: Ready to Merge

#647 Fix: refactor HTTP error codes POST /login for Users service
  app/api/resources/user.py
  tests/users/test_api_login.py
Labels: Status: Ready to Merge

#651 Changed _repr_ string format to f-strings
  app/database/models/mentorship_relation.py
  app/database/models/tasks_list.py
  app/database/models/user.py
Labels: Status: Needs Review

#650 fix: refactor http status code (replace 200 with 201 and 400 with 409)
  app/api/dao/user.py
  app/api/resources/user.py
Labels: Status: Needs Review

#642 fix: Optimize query of unverified users in scheduler
  app/schedulers/delete_unverified_users_cron_job.py
Labels: Category: Coding, Status: Ready to Merge
