Repository anitab-org/mentorship-backend, pull requests merged in 2020-09, with the labels that each got.

#804 Deletion of swagger.json file in mentorship-backend / docs /
  docs/swagger.json
Labels: Open Source Hack, Status: Ready to Merge

#797 Spelling mistake correction in the documentation.
  README.md
Labels: Open Source Hack, Status: Ready to Merge

#810 Added links required
  README.md
Labels: Category: Documentation/Training, Status: Ready to Merge

#792 Removed Link for mentorship systems word in the beginning.
  README.md
Labels: Open Source Hack, Status: Ready to Merge

#805 removed unnecessary imports
  app/database/models/user.py
Labels: Status: Ready to Merge

#822 docs : Updates a line in README.md
  README.md
Labels: Open Source Hack, Status: Ready to Merge

#808 Fixes #742 : Use f-strings in mentorship_relation folder test files
  tests/mentorship_relation/test_api_accept_request.py
  tests/mentorship_relation/test_api_cancel_relation.py
  tests/mentorship_relation/test_api_delete_request.py
  tests/mentorship_relation/test_api_list_relations.py
  tests/mentorship_relation/test_api_reject_request.py
Labels: Open Source Hack, Status: Ready to Merge

#807 docs: add setup and run guide for windows and linux
  README.md
Labels: Status: Changes Requested

#854 Perform manual testing and report PUT /user/change_password #845
  docs/manual_tests/user_change_password.md
Labels: Open Source Hack, Status: Ready to Merge

#832 Docs: updated python badge in readme.md
  README.md
Labels: Open Source Hack, Status: Ready to Merge

#842 fixed the missing module type_ignore for python3.8
  requirements.txt
Labels: Status: Ready to Merge

#849 Docs: Added a table in quality-assurance-test-cases.md
  docs/quality-assurance-test-cases.md
Labels: Open Source Hack, Status: Ready to Merge

#818 docs: add link to quality assurance tables to Swagger UI
  app/api/api_extension.py
Labels: Status: Ready to Merge

#800 fix: run-tests link in README.md
  README.md
Labels: Open Source Hack, Status: Ready to Merge

#891 docs: manual testing report POST /user/refresh
  docs/manual_tests/user_refresh_token.md
Labels: Status: Ready to Merge
