Repository anitab-org/mentorship-backend, pull requests merged in 2020-05, with the labels that each got.

#543 docs: Test PR guide
  docs/test-pr-guide.md
Labels: Category: Documentation/Training

#546 docs: troubleshoots.md - setting Gmail as mail service
  docs/troubleshoots.md
Labels: Category: Documentation/Training

#517 Create Quality Assurance table for Update Task API
  docs/quality-assurance-test-cases.md
Labels: Category: Documentation/Training, Category: Quality Assurance

#567 Fix Swagger UI http response documentation for Task Comment API
  app/api/resources/mentorship_relation.py
Labels: Status: Needs Review

#594 Test pr report
  docs/test-pr-guide.md
Labels: Status: Needs Review

#584 fix error message for password field being blank
  app/api/resources/user.py
  app/messages.py
Labels: Status: Ready to Merge

#541 Add pagination to /users and /users/verified endpoints (issue #279)
  app/api/dao/user.py
  app/api/resources/user.py
  docs/swagger.json
  tests/users/test_api_list_users.py
Labels: Status: Needs Review
