Repository anitab-org/mentorship-backend, pull requests merged in 2020-12, with the labels that each got.

#930 fix: Password accepting empty spaces fixed
  app/api/resources/user.py
  app/api/validations/user.py
  tests/users/test_validation_request_data.py
Labels: Status: Needs Review

#925 fix: Added missing error message
  app/api/resources/user.py
  app/messages.py
  tests/admin/test_api_remove_admin_user.py
Labels: Status: Ready to Merge

#799 Style: Convert string formatting to f-strings in tests/tasks/*
  tests/tasks/test_api_complete_task.py
  tests/tasks/test_api_create_task.py
  tests/tasks/test_api_delete_task.py
  tests/tasks/test_api_list_tasks.py
Labels: Status: Ready to Merge

#861 Fixed, searching based on both the username and name #745
  app/api/dao/user.py
  tests/tasks/test_api_create_task.py
  tests/tasks/test_api_list_tasks.py
  tests/users/test_api_list_users.py
Labels: Status: Ready to Merge

#912 fix : Responses does not list 'Notes field is missing.' error message
  app/api/resources/mentorship_relation.py
Labels: Status: Changes Requested

#943 feat: return user registration_time from get /users
  app/api/models/user.py
  app/api/resources/user.py
Labels: Status: Needs Testing

#936 Refresh Endpoint should mention Refresh token instead of access token
  app/api/resources/common.py
  app/api/resources/user.py
  docs/manual_tests/user_refresh_token.md
Labels: Status: Ready to Merge

#951 heroku app broken links fixed
  app/api/api_extension.py
Labels: Status: Ready to Merge
