Repository anitab-org/mentorship-backend, pull requests merged in 2020-07, with the labels that each got.

#657 docs: Update Travis CI badge and Development server link on README
  README.md
Labels: Category: Documentation/Training, Status: Needs Review

#666 fix: Add local as an option for FLASK_ENVIRONMENT_CONFIG variable in env.template file
  .env.template
Labels: Category: Documentation/Training, Status: Needs Review

#671 fix: refractor HTTP error codes PUT/mentorship_relation/{request_id}/reject
  app/api/dao/mentorship_relation.py
  app/api/resources/mentorship_relation.py
  tests/mentorship_relation/test_dao_reject_mentorship_request.py
Labels: BIT, Status: Ready to Merge

#683 docs: improve and add new documentation
  README.md
  docs/ci_cd_process.md
  docs/code_organization.md
  docs/coding_standards.md
  docs/features.md
  docs/user_authentication.md
Labels: Status: Needs Review

#662 docs: update environment-variables.md
  docs/environment-variables.md
Labels: Status: Needs Review

#604 refactor:add error message for missing username in 400 response
  app/api/resources/user.py
  app/messages.py
Labels: Category: Coding, Category: Documentation/Training, Status: Changes Requested

#688 fixed f string mistake in tests
  tests/task_comments/test_api_create_task_comment.py
  tests/task_comments/test_api_delete_task_comment.py
  tests/task_comments/test_api_get_task_comments.py
  tests/task_comments/test_api_modify_task_comment.py
Labels: Status: Ready to Merge

#682 fix: refactor HTTP error codes POST /mentorship_relation/{request_id}…
  app/api/dao/task.py
  app/api/resources/mentorship_relation.py
  tests/tasks/test_dao_complete_task.py
  tests/tasks/test_dao_create_task.py
Labels: Status: Ready to Merge

#637 refactor: HTTP error codes GET/users/{user_id}
  app/api/resources/user.py
  tests/users/test_api_get_other_user.py
Labels: BIT, Status: Ready to Merge
