Repository anitab-org/mentorship-backend, pull requests merged in 2020-04, with the labels that each got.

#215 docs: update README to include commands to activate venv for windows …
  README.md
Labels: Category: Documentation/Training

#516 Refactor: Improve Swagger Docs description
  app/api/api_extension.py
Labels: Category: Documentation/Training

#502 Update Environment Variables link on README
  README.md
Labels: Category: Documentation/Training

#499 Add Create Task API quality assurance table
  docs/quality-assurance-test-cases.md
Labels: Category: Documentation/Training

#512 Update Environment Variables documentation
  docs/environment-variables.md
Labels: Category: Documentation/Training

#520 issue 507 user not involved in relationship check added along with unit tests
  app/api/dao/task.py
  app/api/resources/mentorship_relation.py
  app/messages.py
  tests/tasks/tasks_base_setup.py
  tests/tasks/test_dao_create_task.py
  tests/test_data.py
Labels: Category: Coding, Needs Testing, Type: Bug

#525 Add mock email service
  .env.template
  README.md
  app/api/email_utils.py
  config.py
  docs/environment-variables.md
Labels: Category: Coding, Review Requested
