Repository anitab-org/mentorship-backend, pull requests merged in 2021-07, with the labels that each got.

#962 test: Create user journey for request rejection
  tests/user_journey/test_rejection_path.py
Labels: Status: Needs Testing

#1129 fix: Swagger documentation HTTP code display
  app/api/resources/mentorship_relation.py
  app/api/resources/task.py
  app/api/resources/task_comment.py
  app/api/resources/user.py
Labels: Status: Needs Testing

#1134 display last 3 achievements
  app/api/dao/user.py
  tests/users/test_api_home_statistics.py
Labels: Status: Ready to Merge

#1136 Add missing tests in Mentorship Relation
  tests/mentorship_relation/test_api_reject_request.py
  tests/mentorship_relation/test_dao_creation.py
Labels: Status: Needs Review

#1030 Error code changed BAD_REQUEST to FORBIDDEN
  app/api/dao/task_comment.py
  app/api/resources/task_comment.py
  tests/task_comments/test_api_create_task_comment.py
  tests/task_comments/test_api_delete_task_comment.py
  tests/task_comments/test_api_get_task_comments.py
  tests/task_comments/test_api_modify_task_comment.py
Labels: Status: Needs Testing

#1121 test: add tests for user file
  app/api/dao/user.py
  tests/users/test_dao.py
  tests/users/test_dao_dashboard.py
  tests/users/test_dao_update_user.py
Labels: Status: Ready to Merge
