Repository anitab-org/mentorship-backend, pull requests merged in 2021-01, with the labels that each got.

#956 Updating Enum representation of status codes to real value in admin.py
  app/api/resources/admin.py
Labels: Status: Ready to Merge

#953 fix: Update http code values instead of expressions
  app/api/resources/user.py
Labels: Status: Needs Testing

#959 Refactor: change response status codes for invalid inputs (409 to 400) in register endpoint
  app/api/resources/user.py
  app/messages.py
  tests/users/test_api_resources.py
Labels: Status: Ready to Merge

#974 docs: update environment variable declarations
  README.md
  docs/environment-variables.md
Labels: Status: Ready to Merge

#734 fix: refactor HTTP error codes POST /mentorship_relation/{relation_id…
  app/api/dao/task_comment.py
  tests/task_comments/test_api_modify_task_comment.py
Labels: Status: Needs Testing

#863 doc: updated reporting_guidelines
  README.md
  docs/code_of_conduct.md
  docs/reporting_guidelines.md
Labels: Status: Ready to Merge

#838 Missing Date field added
  app/api/resources/mentorship_relation.py
Labels: Status: Changes Requested

#983 Fix: Use Real number values of statuscode instead of enum expressions in Swagger
  app/api/resources/mentorship_relation.py
Labels: Status: Ready to Merge

#985 Tests: Use super() without arguments for Python3 only support
  tests/admin/test_api_list_admin_users.py
  tests/admin/test_api_remove_admin_user.py
  tests/cron_job_functions/test_delete_unverified_users_cron.py
  tests/cron_job_functions/test_mentorship_completion_cron.py
  tests/mentorship_relation/relation_base_setup.py
  tests/mentorship_relation/test_api_accept_request.py
  tests/mentorship_relation/test_api_cancel_relation.py
  tests/mentorship_relation/test_api_delete_request.py
  tests/mentorship_relation/test_api_list_relations.py
  tests/mentorship_relation/test_api_reject_request.py
  tests/mentorship_relation/test_api_send_request.py
  tests/mentorship_relation/test_dao_accept_request.py
  tests/mentorship_relation/test_dao_cancel_relation.py
  tests/mentorship_relation/test_dao_creation.py
  tests/mentorship_relation/test_dao_delete_request.py
  tests/mentorship_relation/test_dao_list_relations.py
  tests/mentorship_relation/test_dao_listing.py
  tests/mentorship_relation/test_dao_reject_mentorship_request.py
  tests/tasks/tasks_base_setup.py
  tests/tasks/test_tasks_list_database_model.py
  tests/users/test_api_authentication.py
  tests/users/test_api_change_password.py
  tests/users/test_api_get_other_user.py
  tests/users/test_api_home_statistics.py
  tests/users/test_api_list_users.py
  tests/users/test_api_login.py
  tests/users/test_api_refresh.py
  tests/users/test_dao_dashboard.py
Labels: Status: Needs Testing

#984 Correct setting up virtual env for bash users
  README.md
Labels: Status: Ready to Merge

#982 test : Refactor hard-coded status codes to HTTPstatus in tests
  tests/task_comments/test_api_create_task_comment.py
  tests/task_comments/test_api_delete_task_comment.py
  tests/task_comments/test_api_get_task_comments.py
  tests/task_comments/test_api_modify_task_comment.py
  tests/task_comments/test_dao.py
Labels: Status: Ready to Merge

#970 test: replaced hardcoded response values with HTTPStatus
  tests/mentorship_relation/test_api_accept_request.py
  tests/mentorship_relation/test_api_cancel_relation.py
  tests/mentorship_relation/test_api_delete_request.py
  tests/mentorship_relation/test_api_list_relations.py
  tests/mentorship_relation/test_api_reject_request.py
  tests/mentorship_relation/test_api_send_request.py
  tests/mentorship_relation/test_dao_accept_request.py
  tests/mentorship_relation/test_dao_cancel_relation.py
  tests/mentorship_relation/test_dao_creation.py
  tests/mentorship_relation/test_dao_delete_request.py
  tests/mentorship_relation/test_dao_list_relations.py
  tests/mentorship_relation/test_dao_listing.py
  tests/mentorship_relation/test_dao_reject_mentorship_request.py
Labels: Status: Changes Requested
