Repository anitab-org/mentorship-backend, pull requests merged in 2021-05, with the labels that each got.

#1074 Dev: Add BIT user attributes to MS User
  .github/workflows/main.yml
  app/database/models/user.py
  app/utils/bitschema_utils.py
  migrations/versions/1272e4b54a32_add_user_bitschema_attribute.py
  run.py
Labels: BIT, Category: Coding, Type: Enhancement

#1087 chore: add relevant files to paths-ignore in workflow
  .github/workflows/main.yml
Labels: Status: Ready to Merge

#1076 refactor: Update fetching instructions in test PR guide
  docs/test-pr-guide.md
Labels: Status: Ready to Merge

#716 chore: create config.yml for Welcome Bot
  .github/config.yml
Labels: Status: Ready to Merge

#991 Fix: refactor HTTP error codes PUT /mentorship_relation/{request_id}/cancel
  app/api/dao/mentorship_relation.py
  app/api/resources/mentorship_relation.py
  tests/mentorship_relation/test_api_cancel_relation.py
  tests/mentorship_relation/test_dao_cancel_relation.py
Labels: Status: Ready to Merge

#1090 Doc: Add Run migration script instruction to Readme.
  README.md
Labels: Status: Needs Review

#1099 Update README.md
  README.md
Labels: Status: Ready to Merge
